import type { PositionFilter } from '../config';

export type Lane = Exclude<PositionFilter, 'all'>;

// Curated lane affinity: small nudge on top of the generic role model.
export const LANE_AFFINITY: Record<string, Partial<Record<Lane, number>>> = {
  'Anti-Mage': { 1: 2 },
  Slark: { 1: 2 },
  Ursa: { 1: 2 },
  Lifestealer: { 1: 2 },
  Juggernaut: { 1: 2 },
  'Phantom Assassin': { 1: 2 },
  Terrorblade: { 1: 2 },
  'Faceless Void': { 1: 1.5 },
  Sven: { 1: 1.5, 3: 1 },
  'Drow Ranger': { 1: 2 },
  Medusa: { 1: 2 },
  Spectre: { 1: 2 },
  'Chaos Knight': { 1: 1.5 },
  'Troll Warlord': { 1: 1.5 },
  Morphling: { 1: 1.5, 2: 1 },
  Luna: { 1: 1.5 },
  Gyrocopter: { 1: 1.5 },
  'Monkey King': { 1: 1.5 },
  Puck: { 2: 2 },
  'Queen of Pain': { 2: 2 },
  Lina: { 2: 2 },
  'Storm Spirit': { 2: 2 },
  'Ember Spirit': { 2: 2 },
  'Void Spirit': { 2: 2 },
  Invoker: { 2: 2 },
  Tinker: { 2: 2 },
  'Shadow Fiend': { 2: 2 },
  'Templar Assassin': { 2: 2 },
  Zeus: { 2: 1.5 },
  Sniper: { 2: 1.5 },
  Kunkka: { 2: 1.5, 3: 1 },
  'Death Prophet': { 2: 1.5 },
  'Outworld Destroyer': { 2: 1.5 },
  Pugna: { 2: 1.5 },
  Leshrac: { 2: 1.5 },
  Viper: { 2: 1, 3: 1 },
  'Dragon Knight': { 2: 1, 3: 1 },
  Mars: { 3: 2 },
  Tidehunter: { 3: 2 },
  Axe: { 3: 2 },
  'Centaur Warrunner': { 3: 2 },
  Underlord: { 3: 2 },
  'Legion Commander': { 3: 1.5 },
};
